### ISSUE TITLE
Undeclared Metric Tags

### ISSUE THREAD

**Issue by vterdunov** [yabeda-rb/yabeda-sidekiq#18]
Hi. Thanks for the gems!
I faced to an issue with sidekiq.

rails 5.1.6.2

```bash
cat Gemfile.lock | grep -i sidekiq
    rspec-sidekiq (3.0.3)
      sidekiq (>= 2.4.0)
    sidekiq (5.2.8)
    sidekiq-scheduler (2.2.1)
      sidekiq (>= 3)
    yabeda-sidekiq (0.1.4)
      sidekiq
  rspec-sidekiq
  sidekiq (= 5.2.8)
  sidekiq-scheduler
  yabeda-sidekiq (~> 0.1.1)
```

```bash
cat Gemfile.lock | grep -i yabeda
    yabeda (0.8.0)
    yabeda-prometheus (0.6.1)
      yabeda (~> 0.5)
    yabeda-puma-plugin (0.6.0)
      yabeda (~> 0.5)
    yabeda-rails (0.7.2)
      yabeda (~> 0.8)
    yabeda-sidekiq (0.1.4)
      yabeda
  yabeda-prometheus
  yabeda-puma-plugin
  yabeda-rails
  yabeda-sidekiq (~> 0.1.1)
```

<details>
  <summary>Error logs</summary>

  ```ruby
[28/Apr/2021:18:13:20 +0000] "GET /metrics HTTP/1.1" 500 63162 0.0106                                               
 Yabeda::Prometheus::Adapter::UndeclaredMetricTags: Prometheus requires all used tags to be declared at metric registration time.       
     /usr/local/bundle/gems/yabeda-prometheus-0.6.1/lib/yabeda/prometheus/adapter.rb:55:in `rescue in perform_gauge_set!'               
     /usr/local/bundle/gems/yabeda-prometheus-0.6.1/lib/yabeda/prometheus/adapter.rb:52:in `perform_gauge_set!'                         
     /usr/local/bundle/gems/yabeda-0.8.0/lib/yabeda/gauge.rb:10:in `block in set'                                                       
     /usr/local/bundle/gems/yabeda-0.8.0/lib/yabeda/gauge.rb:9:in `each'                                                                
     /usr/local/bundle/gems/yabeda-0.8.0/lib/yabeda/gauge.rb:9:in `set'                                                                 
     /usr/local/bundle/gems/yabeda-sidekiq-0.1.4/lib/yabeda/sidekiq.rb:43:in `block (3 levels) in <module:Sidekiq>'                     
     /usr/local/bundle/gems/yabeda-sidekiq-0.1.4/lib/yabeda/sidekiq.rb:42:in `each'                                                     
     /usr/local/bundle/gems/yabeda-sidekiq-0.1.4/lib/yabeda/sidekiq.rb:42:in `block (2 levels) in <module:Sidekiq>'                     
     /usr/local/bundle/gems/yabeda-prometheus-0.6.1/lib/yabeda/prometheus/exporter.rb:48:in `each'                                      
     /usr/local/bundle/gems/yabeda-prometheus-0.6.1/lib/yabeda/prometheus/exporter.rb:48:in `call'                                      
     /usr/local/bundle/gems/rack-2.0.9/lib/rack/show_exceptions.rb:23:in `call'                                                         
     /usr/local/bundle/gems/rack-2.0.9/lib/rack/common_logger.rb:33:in `call'                                                           
     /usr/local/bundle/gems/rack-2.0.9/lib/rack/builder.rb:153:in `call'                                                                
     /usr/local/bundle/gems/rollbar-2.15.5/lib/rollbar/middleware/rack/builder.rb:16:in `block in call_with_rollbar'                    
     /usr/local/bundle/gems/rollbar-2.15.5/lib/rollbar.rb:145:in `scoped'                                                               
     /usr/local/bundle/gems/rollbar-2.15.5/lib/rollbar/middleware/rack/builder.rb:14:in `call_with_rollbar'                             
     /usr/local/bundle/gems/rack-2.0.9/lib/rack/handler/webrick.rb:86:in `service'                                                      
     /usr/local/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'                                                                   
     /usr/local/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'                                                                        
     /usr/local/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'     
  ```                               
</details>

Unfortunately, I cannot to reproduce the problem locally.

**Comment by Envek** [comment]
Why your `yabeda-sidekiq` is so old? Current version is 0.7.0

Tags declarations for compatibility with latest Ruby prometheus client [were added](https://github.com/yabeda-rb/yabeda-sidekiq/commit/bc0c2cc47ecd06d0195dbdf3b755b9a1198786bc) in 0.2.0 while you have 0.1.4.

Please upgrade!

**Comment by vterdunov** [comment]
My bad.. it was mindlessly copied from the [example app](https://github.com/yabeda-rb/example-prometheus/blob/62b91201be176ae97d3a3a97d1f2d1d64570af40/rails_app/Gemfile#L22) :)
Will check the proper version.

**Comment by Envek** [comment]
Example app hadn't received updates for a while, that's right. I need to refresh it, thanks for pointing this out

**Comment by vterdunov** [comment]
Upgrade fix the issue. Thanks!
